{% set name = "cx_Freeze" %}
{% set version = "8.5.0" %}
{% set core_name = "freeze-core" %}
{% set core_version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
    sha256: d36e804d393aea1b4ad28cff0d8b8a562cc25ea462f06bcf6b265edbc02eecfb
    folder: cx_Freeze

  - url: https://pypi.org/packages/source/{{ core_name[0] }}/{{ core_name }}/{{ core_name|lower }}-{{ core_version }}.tar.gz
    sha256: 2c8d54000c611b837dc5963eca8561c24fa8a2d67516380312be4e8509ceca86
    folder: freeze-core

build:
  number: 0

outputs:
  - name: {{ core_name|lower }}
    version: {{ core_version }}
    script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      host:
        - python
        - pip
        - setuptools >=78.1.1
        - cx_logging >=3.1       # [win]
      run:
        - python
        - filelock >=3.12.3
        - cabarchive >=0.2.4     # [win]
        - striprtf >=0.0.26      # [win]
    test:
      imports:
        - freeze_core
      requires:
        - coverage >=7.10.3
        - pytest
      source_files:
        - pyproject.toml
        - tests
      commands:
        - coverage run

  - name: {{ name|lower }}
    version: {{ version }}
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    entry_points:
      - cxfreeze = cx_Freeze.cli:main
      - cxfreeze-quickstart = cx_Freeze.setupwriter:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=78.1.1
      run:
        - python >={{ python_min }}
        - freeze-core {{ core_version }}
        - setuptools >=78.1.1
        - packaging >=24.0
        - tomli >=2.0.1          # [py<311]
        - filelock >=3.12.3      # [linux]
        - patchelf >=0.14,<0.18  # [linux]
        - dmgbuild >=1.6.1       # [osx]
        - cx_logging >=3.1       # [win]
        - py-lief >=0.15.1       # [win]
    test:
      imports:
        - cx_Freeze
      requires:
        - coverage >=7.10.3
        - pytest
        - pytest-mock
        - pytest-timeout
        - pytest-xdist
      source_files:
        - pyproject.toml
        - samples
        - tests
      commands:
        - cxfreeze --version
        - coverage run || true

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE.md
  summary: Create standalone executables from Python scripts.
  description: |
    Creates standalone executables from Python scripts with the same
    performance as the original script.
    It is cross-platform and should work on any platform that Python runs on.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
  feedstock-name: {{ name|lower }}
