{% set name = "cx_Freeze" %}
{% set version = "8.5.0" %}
{% set core_name = "freeze-core" %}
{% set core_version = "0.4.0" %}
{% set msi_name = "python-msilib" %}
{% set msi_version = "0.4.2" %}

package:
  name: {{ name|lower }}-feedstock
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ core_name[0] }}/{{ core_name }}/{{ core_name|replace("-", "_") }}-{{ core_version }}.tar.gz
    sha256: d7945b25c09fed6c80bd0e4bec69ac4476f06b2184029d5fd266d9f0a888c9d2
    folder: freeze-core

  - url: https://pypi.org/packages/source/{{ msi_name[0] }}/{{ msi_name }}/{{ msi_name|replace("-", "_") }}-{{ msi_version }}.tar.gz
    sha256: 4655bdfde7be6635b4ef287576a0103684568c5e335dac9e1208ccb6506b774c
    folder: python-msilib

  - git_url: https://github.com/marcelotduarte/cx_Freeze.git
    git_rev: develop
    folder: cx_Freeze
  #- url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  #  sha256: d36e804d393aea1b4ad28cff0d8b8a562cc25ea462f06bcf6b265edbc02eecfb
  #  folder: cx_Freeze

build:
  number: 0

outputs:
  - name: {{ core_name|lower }}
    version: {{ core_version }}
    script: build-freeze-core.bat  # [win]
    script: build-freeze-core.sh   # [not win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      host:
        - python
        - pip
        - setuptools >=78.1.1
        - cx_logging >=3.1       # [win]
      run:
        - python
        - filelock >=3.15.3
        - cabarchive >=0.2.4     # [win]
        - striprtf >=0.0.26      # [win]
        - libxcrypt              # [linux and py<311]
    test:
      imports:
        - freeze_core
      requires:
        - coverage >=7.10.3
        - pytest
      source_files:
        - freeze-core/pyproject.toml
        - freeze-core/tests
      commands:
        - cd freeze-core && coverage run

  - name: {{ msi_name|lower }}
    version: {{ msi_version }}
    script: build-python-msilib.bat
    requirements:
      build:
        skip: true                       # [not win]
        skip: true                       # [py<313]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      host:
        - python
        - pip
        - setuptools >=78.1.1
      run:
        - python
    test:
      imports:
        - msilib
      requires:
        - coverage >=7.10.3
        - pytest
      source_files:
        - python-msilib/pyproject.toml
        - python-msilib/tests
      commands:
        - cd python-msilib && coverage run

  - name: {{ name|lower }}
    version: {{ version }}
    script: build-cx-freeze.bat  # [win]
    script: build-cx-freeze.sh   # [not win]
    entry_points:
      - cxfreeze = cx_Freeze.cli:main
      - cxfreeze-quickstart = cx_Freeze.setupwriter:main
    requirements:
      host:
        - python
        - pip
        - setuptools >=78.1.1
      run:
        - python
        - freeze-core >={{ core_version }}
        - python-msilib >={{ msi_version }}  # [win and py>=313]
        - setuptools >=78.1.1
        - packaging >=24.0
        - tomli >=2.0.1          # [py<311]
        - filelock >=3.15.3      # [linux]
        - patchelf >=0.14,<0.18  # [linux]
        - dmgbuild >=1.6.1       # [osx]
        - cx_logging >=3.1       # [win]
        - py-lief >=0.15.1       # [win]
    test:
      imports:
        - cx_Freeze
      requires:
        - coverage >=7.10.3
        - pytest
        - pytest-mock
        - pytest-timeout
        - pytest-xdist
      source_files:
        - cx_Freeze/pyproject.toml
        - cx_Freeze/samples
        - cx_Freeze/tests
      commands:
        - cxfreeze --version
        - cd cx_Freeze && coverage run || true

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: cx_Freeze/LICENSE.md
  summary: Create standalone executables from Python scripts.
  description: |
    Creates standalone executables from Python scripts with the same
    performance as the original script.
    It is cross-platform and should work on any platform that Python runs on.
  doc_url: https://cx-freeze.readthedocs.io/

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
  feedstock-name: {{ name|lower }}
