schema_version: 1

context:
  name: cx_Freeze
  version: 8.5.0
  sha256: d36e804d393aea1b4ad28cff0d8b8a562cc25ea462f06bcf6b265edbc02eecfb
  core_name: freeze-core
  core_version: 0.4.0
  core_sha256: d7945b25c09fed6c80bd0e4bec69ac4476f06b2184029d5fd266d9f0a888c9d2
  msi_name: python-msilib
  msi_version: 0.4.2
  msi_sha256: 4655bdfde7be6635b4ef287576a0103684568c5e335dac9e1208ccb6506b774c

recipe:
  name: ${{ name|lower }}-feedstock
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ core_name[0] }}/${{ core_name }}/${{ core_name|replace("-", "_") }}-${{ core_version }}.tar.gz
    sha256: ${{ core_sha256 }}
    target_directory: freeze-core
  - url: https://pypi.org/packages/source/${{ msi_name[0] }}/${{ msi_name }}/${{ msi_name|replace("-", "_") }}-${{ msi_version }}.tar.gz
    sha256: ${{ msi_sha256 }}
    target_directory: python-msilib
  - git: https://github.com/marcelotduarte/cx_Freeze.git
    rev: develop
    target_directory: cx_Freeze
  #- url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  #  sha256: ${{ sha256 }}
  #  target_directory: cx_Freeze

build:
  number: 0

outputs:
  - package:
      name: ${{ core_name|lower }}
      version: ${{ core_version }}
    build:
      script:
        - cd freeze-core
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
      host:
        - python
        - pip
        - setuptools >=78.1.1,<81
        - if: win
          then:
            - cx_logging >=3.1
      run:
        - python
        - filelock >=3.15.3
        - if: win
          then:
            - cabarchive >=0.2.4
            - striprtf >=0.0.26
        - if: linux and match(python, "<3.11")
          then:
            - libxcrypt
    tests:
      - python:
          imports:
            - freeze_core
      - files:
          source:
            - freeze-core/pyproject.toml
            - freeze-core/tests
        requirements:
          run:
            - coverage >=7.10.3
            - pytest
        script:
          - cd freeze-core
          - coverage run
  - package:
      name: ${{ msi_name|lower }}
      version: ${{ msi_version }}
    build:
      skip: not (win and match(python, ">=3.13"))
      script:
        - cd python-msilib
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
      host:
        - python
        - pip
        - setuptools >=78.1.1,<81
      run:
        - python
    tests:
      - python:
          imports:
            - msilib
      - files:
          source:
            - python-msilib/pyproject.toml
            - python-msilib/tests
        requirements:
          run:
            - coverage >=7.10.3
            - pytest
        script:
          - cd python-msilib
          - coverage run
  - package:
      name: ${{ name|lower }}
      version: ${{ version }}
    build:
      script:
        - cd cx_Freeze
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      python:
        entry_points:
          - cxfreeze = cx_Freeze.cli:main
          - cxfreeze-quickstart = cx_Freeze.setupwriter:main
    requirements:
      host:
        - python
        - pip
        - setuptools >=78.1.1,<81
      run:
        - python
        - freeze-core >=${{ core_version }}
        - setuptools >=78.1.1,<81
        - packaging >=24.0
        - if: match(python, "<3.11")
          then:
            - tomli >=2.0.1
        - if: linux
          then:
            - filelock >=3.15.3
            - patchelf >=0.14,<0.18
        - if: osx
          then:
            - dmgbuild >=1.6.1
        - if: win
          then:
            - cx_logging >=3.1
            - py-lief >=0.15.1
        - if: win and match(python, ">=3.13")
          then:
            - python-msilib >=${{ msi_version }}
    tests:
      - python:
          imports:
            - cx_Freeze
          pip_check: false
      - files:
          source:
            - cx_Freeze/pyproject.toml
            - cx_Freeze/samples
            - cx_Freeze/tests
        requirements:
          run:
            - coverage >=7.10.3
            - pytest
            - pytest-mock
            - pytest-timeout
            - pytest-xdist
        script:
          - cxfreeze --version
          - if: not (osx and x86_64)
            then: coverage run || true

about:
  license: PSF-2.0
  license_file: cx_Freeze/LICENSE.md
  summary: Create standalone executables from Python scripts.
  description: |
    Creates standalone executables from Python scripts with the same
    performance as the original script.
    It is cross-platform and should work on any platform that Python runs on.
  homepage: https://marcelotduarte.github.io/cx_Freeze
  documentation: https://cx-freeze.readthedocs.io/

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
  feedstock-name: ${{ name|lower }}
