schema_version: 1

context:
  name: cx_Freeze
  version: "8.6.0"
  sha256: 04de4e97a0fbebf5c67aec74ecd62c206f282163a111cda4343367d653b2c46d

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cxfreeze = cx_Freeze.cli:main
      - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - setuptools >=78.1.1,<=82.0
  run:
    - python
    - freeze-core >=0.6.0
    - packaging >=25.0
    - setuptools >=78.1.1,<=82.0
    - if: match(python, "<3.11")
      then:
        - tomli >=2.0.1
    - if: linux
      then:
        - filelock >=3.20.3
        - patchelf >=0.14,<0.18
    - if: osx
      then:
        - dmgbuild >=1.6.1
    - if: win
      then:
        - py-lief >=0.15.1
    - if: win and match(python, "==3.13")
      then:
        - python-msilib >=0.4.3

tests:
  - python:
      imports:
        - cx_Freeze
      pip_check: false
  - files:
      source:
        - pyproject.toml
        - samples
        - tests
    requirements:
      run:
        - coverage >=7.10.3
        - pytest >=9.0.2
        - pytest-mock
        - pytest-timeout
        - pytest-xdist
    script:
      - cxfreeze --version
      - if: not (osx and x86_64)
        then: coverage run || true

about:
  license: PSF-2.0
  license_file: LICENSE.md
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.
  homepage: https://marcelotduarte.github.io/cx_Freeze

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
