schema_version: 1

context:
  name: cx_Freeze
  version: "8.7.1"
  sha256: 05c09b447cab2f3ee4512c2478e745c46323d079c61df6db501e01975ba4d3a5
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cxfreeze = cx_Freeze.cli:main
      - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools ==84.0
  run:
    - __${{ noarch_platform }}
    - python >=${{ python_min }}
    - freeze-core ==0.6.1
    - packaging >=25.0
    - setuptools >=78.1.1,<85.0
    - ${{ "filelock >=3.20.3" if noarch_platform == "linux" }}
    - ${{ "patchelf >=0.14,!=0.18.*" if noarch_platform == "linux" }}
    - ${{ "dmgbuild >=1.6.1" if noarch_platform == "osx" }}
    - ${{ "py-lief >=0.16.1,<1.1.0" if noarch_platform == "win" }}
    - ${{ "python-msilib >=0.4.3" if noarch_platform == "win" }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - cx_Freeze
      pip_check: false
  - files:
      source:
        - pyproject.toml
        - samples
        - tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - coverage >=7.13.0
        - filelock >=3.20.3
        - pytest >=9.0.3
        - pytest-mock
        - pytest-timeout
        - pytest-xdist
    script:
      - cxfreeze --version
      - coverage run || true

about:
  license: PSF-2.0
  license_file: LICENSE.md
  summary: Creates standalone executables from Python scripts with the same performance as the original script. It is cross-platform and should work on any platform that Python runs on.
  homepage: https://marcelotduarte.github.io/cx_Freeze

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
